### ISSUE TITLE
Direction of polarity of C1 and C2

### ISSUE THREAD

**Issue by takishim** [girishji/optical-keyboard-mx#1]
Hi,
When outputting a CPL file, are the polarity directions of C1 and C2 reversed?
https://jlcpcb.com/partdetail/KyoceraAvx-TAJA106K016RNJ/C7171

**Comment by takishim** [comment]
Hi, what about this issue?

**Comment by girishji** [comment]
Probably not, but it is important not to reverse polarity (otherwise those tantalums will burn out and short).
C1: GND is 1 (top), VCC is 2. This means the anode marker should point down.
C2: anode marker should point to the right

**Comment by takishim** [comment]
![2022-12-28 075501](https://user-images.githubusercontent.com/96878459/209733786-528f3978-872a-4d8e-9cea-1a5d921cce97.jpg)
As far as checking C7171 in jlcpcb, it seems VCC(anode) is 1 and GND(cathode) is 2.
